### ISSUE TITLE
サーバーで指定するIPアドレスを外部アドレスに修正する

### ISSUE THREAD

**Issue by Sorasky4** [FunLocks/team2005#26]
back/app.pyのapp.run(host='0.0.0.0', debug=True)となっているところで外部アドレスを指定する
0.0.0.0はOS依存で勝手にローカルホスト(127.0.0.1)に変換されることがあるローカルマシン上の全てのIPv4アドレスであるため、外部からのアクセスを受け付けない

**Comment by marbou090** [comment]
そもそも消しても動くんだけど、消す方向じゃなく外部アドレスにしたほうがよい？

**Comment by Sorasky4** [comment]
消しても動くっていうのは、指定を消したらアプリを走らせたときにhttp://127.0.0.1:5000/になるって認識で良いかな？
だとすると、例えばまるの環境で走らせているのに対してこっちからアクセスできなくない？(実際は各アンドロイド端末から)
なので、外部アドレスにしないと動かないと思う

**Comment by marbou090** [comment]
ローカルサーバで手元で試すときは確かに空パパ見れないけど、herokuにあげたらherokuのアドレスで動くわけだからよいのでは？？
実際こたくんのPCからもjsonファイル見れたのは昨日確認したわけだし…
