### ISSUE TITLE
おすすめのノートPCスタンド

### ISSUE THREAD

**Issue by marbou090** [FunLocks/team2005#27]
首が痛いので買おうと思います
オススメ教えてください

**Comment by Atria64** [comment]
これが気になります。めっちゃコンパクトかつ軽い。
[国内正規代理店 MOFT 超軽量 ノートスタンド Adhesive Foldable Laptop Stand (ピンク) MOFT](https://www.amazon.co.jp/dp/B07TW48BKH/ref=cm_sw_r_tw_dp_3AD2FbQ6PQCHS?_x_encoding=UTF8&psc=1)

**Comment by Sorasky4** [comment]
ちょっとちゃっちいけど機能的には好き
https://www.amazon.co.jp/gp/product/B0824JXWLH/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&th=1
