### ISSUE TITLE
端末がビーコンを検知

### ISSUE THREAD

**Issue by marbou090** [FunLocks/team2005#8]
#5 のために必要

**Comment by kota-shiokara** [comment]
びこーんの検知頻度どうしよって思ったけどBLEだし常駐で良さげ？
それでもバッテリー消費えぐそう

**Comment by marbou090** [comment]
消費えぐすぎるの嫌だからなぁ
5分に一回くらいで、ユーザーが今すぐスキャン押したらもう一回みたいなイメージだった。

**Comment by kota-shiokara** [comment]
混雑度測るためのびこーんって、サーバーに現在地を送るためのものなのよね
昨日実装したBluetoothの方は、周囲のデバイスを検知するためのものだから15分とかに一回検知～って感じで

**Comment by marbou090** [comment]
現在地更新5分程度じゃだめかな
常時ぴこぴこ動いてもかわいいけど
1分とかぐらいでもよいのじゃと思う

**Comment by kota-shiokara** [comment]
五分に一回現在地更新にすっかあ
混雑度予想だからあれだよね、バックグラウンドでも点いててほしい感じよね？

**Comment by kota-shiokara** [comment]
五分か十分に一回(頻度はあとで調整)取ってきて前回のIDと違う若しくは範囲内にビーコンあるかないかで色いろ測れそうだね
